version: '3.5'
services:
  ikev2-server:
    build:
      context: ./
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    ports:
      - 500:500/udp
      - 4500:4500/udp
    privileged: true
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/live/open.ripe.one:/etc/ipsec.d/cacerts/
      - /etc/letsencrypt/live/open.ripe.one:/etc/ipsec.d/private/
      - /lib/modules:/lib/modules:ro
